version: '3.8'
services:
  postgresNew:
    image: postgres:latest
    container_name: blok-postgres-new
    ports:
      - "5433:5432"  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hothanhtienqb123
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  app:
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: my-blog-app
    ports:
      - "6000:4000" 
    env_file: ".env"
    depends_on:
      - postgresNew 

volumes:
  postgres_data: 
