version: '3.8'
services:
  postgresNew:
    image: postgres:latest
    container_name: blok-postgres-new
    ports:
      - "5433:5432"  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hothanhtienqb123
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  app:
    image: hothanhtien/my-blog-app:latest
    container_name: my-blog-app
    ports:
      - "6000:4000" 
    environment:
      DB_HOST: ${DB_HOST_SERVER} #postgresNew 
      DB_USER: ${DB_USER_SERVER} #postgres
      DB_PASS: ${DB_PASS_SERVER} #hothanhtienqb123
      DB_NAME: ${DB_NAME_SEVER}  #mydatabase
      JWT_SECRET: ${JWT_SECRET}    #12345
      SALT_ROUND: ${SALT_ROUND}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      - postgresNew 

volumes:
  postgres_data: 
